---
version: 2
updates:
 - package-ecosystem: "terraform"
   directory: "/"
   schedule:
     interval: "daily"
   reviewers:
      - "cam3ron2"
    labels:
      - "go"
      - "dependencies"
    open-pull-requests-limit: 1
